// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculate_loudness_cpp
List calculate_loudness_cpp(NumericVector inputF, NumericVector inputLdB, NumericVector HLcf, NumericVector HLohcdB0, NumericVector HLihcdB0, int NoChan, double E_Beg, double E_End, int Binaural);
RcppExport SEXP _SII_calculate_loudness_cpp(SEXP inputFSEXP, SEXP inputLdBSEXP, SEXP HLcfSEXP, SEXP HLohcdB0SEXP, SEXP HLihcdB0SEXP, SEXP NoChanSEXP, SEXP E_BegSEXP, SEXP E_EndSEXP, SEXP BinauralSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type inputF(inputFSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type inputLdB(inputLdBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type HLcf(HLcfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type HLohcdB0(HLohcdB0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type HLihcdB0(HLihcdB0SEXP);
    Rcpp::traits::input_parameter< int >::type NoChan(NoChanSEXP);
    Rcpp::traits::input_parameter< double >::type E_Beg(E_BegSEXP);
    Rcpp::traits::input_parameter< double >::type E_End(E_EndSEXP);
    Rcpp::traits::input_parameter< int >::type Binaural(BinauralSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_loudness_cpp(inputF, inputLdB, HLcf, HLohcdB0, HLihcdB0, NoChan, E_Beg, E_End, Binaural));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SII_calculate_loudness_cpp", (DL_FUNC) &_SII_calculate_loudness_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_SII(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
