## fig_budget.R --------------------------------------------------------------
## The loudness budget decomposition, as a figure.
##
## Table 2 reports L_0 and L_cap for seven profiles at three input levels: 42
## numbers from which the reader must compute the fraction consumed. The claim
## those numbers support is simple and spatial — for the precipitous profiles
## the unamplified speech already fills most of the ceiling, while for the mild
## and moderate profiles it does not — so it belongs in a figure.
##
## Input:  reproducibility_scripts/output/jaaa_audmod/table1_budget_decomposition.csv
##         (produced by gen_budget_decomposition.R; the file name predates the
##          manuscript's table renumbering)
## Output: figures/Figure1_Loudness_Budget.png / .pdf
##
## Profiles are labelled by code only; the caption points at the table that
## defines them. Greyscale-safe: the two segments are distinguished by fill
## value and border, not by colour. Read-only; no optimizer.
## Run from the repository root.
## -----------------------------------------------------------------------------

library(ggplot2)
suppressMessages(library(dplyr))
suppressMessages(library(tidyr))

in_csv  <- "reproducibility_scripts/output/jaaa_audmod/table1_budget_decomposition.csv"
out_dir <- "figures"
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

stopifnot(file.exists(in_csv))
d <- read.csv(in_csv, stringsAsFactors = FALSE)

## Drop the normal-hearing reference rows; L_cap is defined from them, so they
## would plot as a full bar by construction.
d <- d %>% dplyr::filter(Profile != "Normal")

d <- d %>%
  dplyr::mutate(
    profile_f = factor(toupper(Profile), levels = paste0("A", 1:7)),
    level_f = factor(Level, levels = c(50, 65, 80),
                     labels = paste0(c(50, 65, 80), " dB SPL")),
    consumed = L0,
    remaining = pmax(0, Lcap - L0),
    pct = 100 * L0 / Lcap)

long <- d %>%
  dplyr::select(profile_f, level_f, consumed, remaining) %>%
  tidyr::pivot_longer(c(consumed, remaining), names_to = "part",
                      values_to = "sones") %>%
  dplyr::mutate(part = factor(part, levels = c("remaining", "consumed"),
                              labels = c("Remaining budget",
                                         "Consumed by unamplified speech")))

## Label the consumed fraction above each bar.
labs_df <- d %>%
  dplyr::mutate(lab = sprintf("%.0f%%", pct)) %>%
  dplyr::select(profile_f, level_f, Lcap, lab)

g <- ggplot(long, aes(x = profile_f, y = sones, fill = part)) +
  geom_col(width = 0.7, colour = "grey25", linewidth = 0.3) +
  geom_text(data = labs_df,
            aes(x = profile_f, y = Lcap, label = lab),
            inherit.aes = FALSE, vjust = -0.5, size = 2.8, colour = "grey20") +
  scale_fill_manual(name = NULL,
                    values = c("Remaining budget" = "grey92",
                               "Consumed by unamplified speech" = "grey45")) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.12))) +
  facet_wrap(~ level_f, nrow = 1, scales = "free_y") +
  labs(x = "Audiometric profile", y = "Loudness (sones)",
       caption = paste0(
         "Profiles as defined in Table 1. Each bar is the normative ceiling for that input level, identical across listeners.\n",
         "The dark segment is the loudness of unamplified speech generated by residual hearing; the light segment is what\n",
         "remains to purchase high-frequency audibility. Percentages give the fraction of the ceiling consumed before any\n",
         "gain is prescribed.")) +
  theme_minimal(base_size = 10) +
  theme(legend.position = "bottom",
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        axis.text.x = element_text(size = 9),
        plot.caption = element_text(hjust = 0, size = 7.5, colour = "grey30"))

ggsave(file.path(out_dir, "Figure1_Loudness_Budget.png"), g,
       width = 9.5, height = 4.4, dpi = 300, bg = "white")
ggsave(file.path(out_dir, "Figure1_Loudness_Budget.pdf"), g,
       width = 9.5, height = 4.4, bg = "white")

cat("Fraction of the ceiling consumed by unamplified speech (%):\n")
print(as.data.frame(
  d %>% dplyr::mutate(pct = round(pct, 1)) %>%
    tidyr::pivot_wider(names_from = Level, values_from = pct,
                       id_cols = Profile)))

cat("\nWritten to", out_dir, "\n")
