# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Canonical Loudness (Native C++ Engine)
#' 
#' Native C++ port of the bramslow2004 canonical engine, corrected per
#' AMToolbox 1.6.0 reference with noted simplifications.
#' 
#' @param inputF Vector of input frequencies (Hz)
#' @param inputLdB Vector of input spectrum levels (dB/Hz, free field)
#' @param HLcf Audiogram frequencies (Hz)
#' @param HLdB Total hearing loss at audiogram frequencies (dB HL)
#' @param NoChan Number of ERB channels (default 30)
#' @param E_Beg Lowest ERB rate (default 3.0)
#' @param E_End Highest ERB rate (default 32.0)
#' @param Binaural Integer indicating whether to compute binaural loudness (default 0L)
#' @return A list containing Loudness (sones), Excitation, Cams, and CFs.
#' @export
calculate_loudness_cpp <- function(inputF, inputLdB, HLcf, HLdB, NoChan = 30L, E_Beg = 3.0, E_End = 32.0, Binaural = 0L) {
    .Call(`_SII_calculate_loudness_cpp`, inputF, inputLdB, HLcf, HLdB, NoChan, E_Beg, E_End, Binaural)
}

